EVENTLOG_INFORMATION_TYPE: int
PYS_SERVICE_STARTED: int

def Initialize() -> None: ...
def PrepareToHostSingle(cls: type[object]) -> None: ...
def StartServiceCtrlDispatcher() -> None: ...
def LogMsg(eventType: int, eventID: int, data: tuple[str, str]) -> None: ...
def LogErrorMsg(message: str) -> None: ...
